<?php
$labels = array();
$labels['shownotifies'] = 'Десктоп нотификации';
$labels['onlynew'] = 'Показвай само нови съобщения';
$labels['conf_browser'] = 'Конфигуриране на браузъра';
$labels['test_browser'] = 'Тестване';
$labels['excluded_directories'] = 'Изключени директории за нотификации';
$labels['check_ok'] = 'Настройките на браузъра ви са правилни.';
$labels['check_fail'] = 'Не беше възможно да се покаже нотификация, моля, кликнете "Конфигуриране на браузъра"!';
$labels['check_fail_blocked'] = 'Вашият браузър блокира нотификациите, моля, задайте разрешение в настройките на браузъра!';
$labels['no_notifications'] = 'Вашият браузър не поддържа десктоп нотификации!';
$labels['ok_notifications'] = 'Уебсайтът вече има разрешение. Десктоп нотификациите би трябвало да работят.';
$labels['notification_title'] = 'Ново имейл съобщение от [from]';

$labels['seconds'] = 'секунди';
$labels['off'] = 'изключено';
$labels['durable'] = 'постоянно';

$labels['no_mailbox'] = 'не показвай пощенската кутия';
$labels['short_mailbox'] = 'показвай кратко име на пощенската кутия';
$labels['full_mailbox'] = 'показвай пълно име на пощенската кутия';

$labels['notifier_popuptype'] = 'Как да се отвори съобщението при клик върху нотификацията';
$labels['new_tab'] = 'В нов раздел';
$labels['new_window'] = 'В нов прозорец';
?>
