<?php
$labels = array();
$labels['shownotifies'] = 'Notificações no Ambiente de trabalho';
$labels['onlynew'] = 'Mostrar apenas novas mensagens';
$labels['conf_browser'] = 'Configurar o navegador';
$labels['test_browser'] = 'Testar';
$labels['excluded_directories'] = 'Pastas excluídas das notificações';
$labels['check_ok'] = 'As definições do seu navegador estão corretas.';
$labels['check_fail'] = 'Não foi possível mostrar a notificação, clique em "Configurar o navegador"!';
$labels['check_fail_blocked'] = 'O seu navegador bloqueou a notificação, ative a permissão nas definições do navegador!';
$labels['no_notifications'] = 'O seu navegador não suporta Notificações no Ambiente de trabalho!';
$labels['ok_notifications'] = 'A página já obteve permissão. As Notificações no Ambiente de trabalho devem funcionar.';
$labels['notification_title'] = 'Novo e-mail de [from]';

$labels['seconds'] = 'segundos';
$labels['off'] = 'desativado';
$labels['durable'] = 'permanente';

$labels['no_mailbox'] = 'não mostrar caixa de correio';
$labels['short_mailbox'] = 'mostrar caixa de correio curta';
$labels['full_mailbox'] = 'mostrar caixa de correio completa';

$labels['notifier_popuptype'] = 'Como abrir mensagens ao clicar na notificação';
$labels['new_tab'] = 'Numa nova aba';
$labels['new_window'] = 'Numa nova janela';
?>
